version: '3.8'

services:
  web:
    container_name: psychonauts
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - 3000:3000
